### PR TITLE
Http and more

### PR DESCRIPTION
**Pull request by kesla**
Adding as much node net-compability to be able to run some basic http-commands!

### CODE REVIEW

**Comment by kesla** [comment]
@iefserge Hey, this last one is failing for me - I get something like this:

```
# createServer listen to port
ok 1 correct port
ok 2 correct address
ok 3 correct family
# createServer() listen to port & address
ok 4 correct port
ok 5 correct address
ok 6 correct family
# createServer() listen to port 0
ok 7 correct port
ok 8 correct address
ok 9 correct family
# createServer() subscribe to events
ok 10 events are async
# createServer() listen, close, listen and close
ok 11 correct port
ok 12 address() null
ok 13 correct port
ok 14 close & listen are async
ok 15 address() null
# createConnection && connect
ok 16 createConnection & connect are the same
# createServer() & createConnection()
ok 17 should be equal
ok 18 should be equal
# createServer() with callback
ok 19 should be equal
# createConnection() local with ip and callback
# createConnection() local with object
[ terminate thread (reason: refcount 0) ]
Kernel error: Assertion failed: resource_ && "Using empty handle." (src/kernel/resource.h: getUnsafe: 58)
```

but the tests in themselves all seem to work - so it's the combination of running this stuff that is failing.

**Comment by iefserge** [comment]
@kesla should be fixed now

**Comment by kesla** [comment]
@iefserge hey, no it still doesn't work for me - same error as before...

**Comment by iefserge** [comment]
@kesla what's the versions of runtime kernel/corelib are you using?

**Comment by kesla** [comment]
@iefserge runtime-tools@0.5.0 & runtimejs@0.1.11 - I don't know what version of kernal/corelib that corresponds to :)

**Comment by kesla** [comment]
@iefserge nevermind, this is working now. I was running it on an old version.. Sorry!

**Comment by iefserge** [comment]
nice!
btw, I added versions output like

```
v0.1.8 kernel
v0.1.11 core library
```

**Comment by kesla** [comment]
@iefserge You wanna review this?

**Comment by iefserge** [comment]
@kesla this is awesome!!
dns api is a bit awkward and it doesn't resolve localhost, going to need to fix this :)

**Comment by kesla** [comment]
@iefserge actually, I'm working on `runtime-node-dns` - a dns module that's compatible with node.js fns-module... So if you're working on the dns-api - add support to get the ttl!

**Comment by iefserge** [comment]
@kesla nice, node-style dns module :+1:

**Pull request merged**
